### ISSUE TITLE
Add symfony/deprecation-contracts to support 3.0 too?

### ISSUE THREAD

**Issue by wizhippo** [netgen-layouts/content-browser#10]

**Comment by emodric** [comment]
Hi @wizhippo,

In `layouts-core`, `symfony/deprecation-contracts` 3.0 is allowed only in still unreleased `master` branch. Is the same okay here, or do you require this in v1.3 ?

**Comment by wizhippo** [comment]
master is fine for now.

I'm cheating at the moment and using  "symfony/deprecation-contracts": "v3.1.1 as 2.5" as even more packages are affected.

**Comment by emodric** [comment]
Done!
