### ISSUE TITLE
ezlocation support?

### ISSUE THREAD

**Issue by wizhippo** [netgen-layouts/content-browser#4]
Trying out netgen layouts and I'm getting ' Netgen Content Browser backend for "ezlocation" value type does not exist.'  Ideas?

**Comment by emodric** [comment]
Maybe missing this? https://github.com/netgen-layouts/content-browser-ezplatform :)

**Comment by wizhippo** [comment]
I have it and have Netgen\Bundle\ContentBrowserEzPlatformBundle\NetgenContentBrowserEzPlatformBundle(), in the app.

**Comment by wizhippo** [comment]
Got it.  The order of the bundles is important.  Silly me I sorted them.

**Comment by emodric** [comment]
We still need proper docs, obviously :)
